import http from 'http';
import "core-js/stable";
import "regenerator-runtime/runtime";

// const server = http.createServer((req, res) => {
//   const ip = res.socket.remoteAddress;
//   const port = res.socket.remotePort;
//   res.end(`Your IP address is ${ip} and your source port is ${port}.`);
// })
//
// server.listen(3000);

import { Readable, pipeline } from 'stream'
import fs from 'fs'
import randomWords from 'random-words'

const length = 2000
const words = ['Rock', 'Paper', 'Scissors']

function * generate() {
  yield 'ID Number,Email,First Name,Last Name,Authentication Method,Display Language,Country,City,Address,Phone number,Institution,Department,Status,Hierarchy Path,Org Framework,Restriction 1,Restriction 2\n'

  let i = 0
  while (i < length) {
    const randomNumber = Math.random().toFixed(10).split('.')[1]
    const conID = `CON-${randomNumber}`
    const word1 = randomWords()
    const firstName = word1.charAt(0).toUpperCase() + word1.slice(1)
    const word2 = randomWords()
    const lastName = word2.charAt(0).toUpperCase() + word2.slice(1)
    yield `${conID},${firstName}.${lastName}@wssdh.net,${firstName},${lastName},SAML2,English,,,,,,,Active,,ICA,,\n`
    i += 1
  }
}

const readable = Readable.from(generate());
const writable = fs.createWriteStream('./autogenerated.csv')

pipeline(
  readable,
  writable,
  (err) => {
  if (err) {
    console.error('Pipeline failed.', err);
  } else {
    console.log('Pipeline succeeded.');
  }
})
